import { shuffle } from '../utils/index'

interface Emoji {
    [key: string]: string
}

export const foodEmojis: Emoji = {
    apple: '🍎',
    baby_bottle: '🍼',
    banana: '🍌',
    beer_mug: '🍺',
    bento_box: '🍱',
    birthday_cake: '🎂',
    bottle_with_popping_cork: '🍾',
    bread: '🍞',
    burrito: '🌯',
    candy: '🍬',
    cheese: '🧀',
    cherries: '🍒',
    chestnut: '🌰',
    chocolate_bar: '🍫',
    cocktail_glass: '🍸',
    cooked_rice: '🍚',
    cookie: '🍪',
    cooking: '🍳',
    corn: '🌽',
    croissant: '🥐',
    custard: '🍮',
    dango: '🍡',
    doughnut: '🍩',
    ear_of_corn: '🌽',
    eggplant: '🍆',
    fish_cake_with_swirl: '🍥',
    french_fries: '🍟',
    fried_shrimp: '🍤',
    grapes: '🍇',
    green_apple: '🍏',
    hamburger: '🍔',
    honeydew: '🍈',
    honey_pot: '🍯',
    hot_beverage: '☕',
    hotdog: '🌭',
    hot_pepper: '🌶️',
    ice_cream: '🍨',
    lemon: '🍋',
    loadofbread: '🍞',
    lollipop: '🍭',
    meat_on_bone: '🍖',
    melon: '🍈',
    mushroom: '🍄',
    orange: '🍊',
    pancakes: '🥞',
    peach: '🍑',
    pear: '🍐',
    pineapple: '🍍',
    pizza: '🍕',
    popcorn: '🍿',
    pot_of_food: '🍲',
    poultry_leg: '🍗',
    oden: '🍢',
    rice_ball: '🍙',
    rice_cracker: '🍘',
    roasted_sweet_potato: '🍠',
    sake: '🍶',
    shaved_ice: '🍧',
    shortcake: '🍰',
    soft_ice_cream: '🍦',
    steaming_bowl: '🍜',
    spaghetti: '🍝',
    strawberry: '🍓',
    sushi: '🍣',
    taco: '🌮',
    teacup_without_handle: '🍵',
    tomato: '🍅',
    tropical_drink: '🍹',
    watermelon: '🍉',
    wine_glass: '🍷',
}

export const animalEmojis: Emoji = {
    ant: '🐜',
    bear_face: '🐻',
    bird: '🐦',
    blowfish: '🐡',
    boar: '🐗',
    bug: '🐛',
    camel: '🐪',
    cat: '🐈',
    cat_face: '🐱',
    chicken: '🐔',
    chipmunk: '🐿️',
    cow: '🐄',
    cow_face: '🐮',
    crab: '🦀',
    crocodile: '🐊',
    dog_face: '🐶',
    dog: '🐕',
    dove: '🕊',
    elephant: '🐘',
    ewe: '🐑',
    frog_face: '🐸',
    goat: '🐐',
    hamster_face: '🐹',
    honeybee: '🐝',
    horse: '🐎',
    horse_face: '🐴',
    koala: '🐨',
    leopard: '🐆',
    lion_face: '🦁',
    monkey: '🐒',
    monkey_face: '🐵',
    mouse: '🐁',
    mouse_face: '🐭',
    octopus: '🐙',
    ox: '🐂',
    panda_face: '🐼',
    penguin: '🐧',
    pig: '🐖',
    pig_face: '🐷',
    pig_nose: '🐽',
    rabbit: '🐇',
    rabbitface: '🐰',
    ram: '🐏',
    rat: '🐀',
    roster: '🐓',
    scorpion: '🦂',
    snake: '🐍',
    snail: '🐌',
    spider: '🕷️',
    tiger: '🐅',
    tiger_face: '🐯',
    two_hump_camel: '🐫',
    turkey: '🦃',
    turtle: '🐢',
    unicorn: '🦄',
    water_buffalo: '🐃',
    wolf_face: '🐺',
    whale: '🐋'
}

export const foods = shuffle(Object.values(foodEmojis))
export const animals = shuffle(Object.values(animalEmojis))
export const allEmojis = shuffle([...Object.values(foodEmojis), ...Object.values(animalEmojis)])
